image: node:14-alpine

services:
  - docker:19.03.13-dind

# global cache (apply for all jobs in all stages)

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - install
  - linting

# install npm dependencies so it'll be cache in subsequent jobs
# note: we can't do this in linting stage as in that stage, 2 jobs run concurrently and both need node_modules

install_dependencies:
  stage: install
  script:
    - yarn install

# this job make sure code is linted
lint-code:
  stage: linting
  script:
    - yarn lint